### ISSUE TITLE
writeback_cache performance drops

### ISSUE THREAD

**Issue by apeters1971** [libfuse/libfuse#37]
Hi, 
I am experimenting with Kernel 4.5.0-1(EL7) and the master branch of today of libfuse and the writeback cache feature. 

I observe that the FUSE fs stalls for some time.

[root@fuse3 example]# **./fusexmp_fh -o writeback_cache /mnt**
[root@fuse3 example]# dd if=/dev/zero of=/mnt/tmp/wb bs=1M count=40
40+0 records in
40+0 records out
41943040 bytes (42 MB) copied, 0,41428 s, 101 MB/s
[root@fuse3 example]# dd if=/dev/zero of=/mnt/tmp/wb bs=1M count=40
40+0 records in
40+0 records out
**41943040 bytes (42 MB) copied, 4,22575 s, 9,9 MB/s**
[root@fuse3 example]# dd if=/dev/zero of=/mnt/tmp/wb bs=1M count=40
40+0 records in
40+0 records out
41943040 bytes (42 MB) copied, 0,366669 s, 114 MB/s
[root@fuse3 example]# dd if=/dev/zero of=/mnt/tmp/wb bs=1M count=40
40+0 records in
40+0 records out
**41943040 bytes (42 MB) copied, 33,6292 s, 1,2 MB/s**

Enabling the low-level debug when using it with my own FUSE module (where it behaves the same) i can see, that everything in user space runs perfectly fine and after sending a response to flush there are no new requests coming for some time.

I see the same behaviour with Kernel 4.4.0.

Not sure it is important. The host is a VM. 

Thanks Andreas.

**Comment by Nikratio** [comment]
Thanks for the report!

As far as I can tell, this is a problem with *FUSE*, the Linux kernel module. This GitHub project is primarily for *libfuse*, the userspace library. I'm happy to keep track of kernel issues in this  issue tracker as well, but please note that it's quite unlikely that reporting kernel issues here will be sufficient to get them fixed. 

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, e.g. [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) or [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel).

**Comment by apeters1971** [comment]
FYI, I figured out that this issue is fixed by
 https://lkml.org/lkml/2016/3/10/21
but it is not yet merged into the 4.5.x release.
I have verified by applying this patch that the write-back cache works.

**Comment by AkilRaza** [comment]
Actually I could Still See the Problem when using 4.10 Kernel . First I found the Problem using 3.18 Kernel Then I tried on Kernel 4.10. When the iozone was used to Write in the Mount Point .From the stap debugging I found the io schedule time out is seen. And the 128 K Data is Send to USer Space in interval of 1s

[err_log_blacnedirtypage.txt](https://github.com/libfuse/libfuse/files/1001786/err_log_blacnedirtypage.txt)

**Comment by guoying1030** [comment]
@apeters1971  what version kernel you use ???can slove it ?

**Comment by guoying1030** [comment]
@AkilRaza   how to fix it ?
